import home from "./home.png";

export const IMAGES = {
  home: require("./home.png"),
  academic: require("./academic.png"),
  community: require("./community.png"),
  information: require("./information.png"),
  ai: require("./ai.png"),
  planner: require("./planner.png"),
  money: require("./money.png"),
  time: require("./time.png"),
  success: require("./success.png"),
  blog1: require("./blog1.png"),
  blog2: require("./blog2.png"),
  blog3: require("./blog3.png"),
  people: require("./people.png"),
  uni1: require("./university1.png"),
  uni2: require("./university2.png"),
  uni3: require("./university3.png"),
  uni4: require("./university4.png"),
  contactBg: require("./contactbg.png"),
  programsBg: require("./programs.png"),
  barcelona: require("./barcelona.png"),
  madrid: require("./madrid.png"),
  barca1: require("./barca1.png"),
  barca2: require("./barca2.jpeg"),
  barca3: require("./barca3.jpeg"),
  barca4: require("./barca4.jpeg"),
  barca5: require("./barca5.jpeg"),
  house: require("./house.png"),
  cart: require("./cart.png"),
  beer: require("./beer.png"),
  cash: require("./cash.png"),
  sunny: require("./sunny.png"),
  partially: require("./partially.png"),
  rain: require("./rain.png"),
  esp1: require("./uni1.jpeg"),
  esp2: require("./uni2.jpeg"),
  esp3: require("./uni3.jpeg"),
  esp4: require("./uni4.jpeg"),
  esp5: require("./uni5.png"),
  madrid1: require("./madrid1.jpg"),
  madrid2: require("./madrid2.jpg"),
  madrid3: require("./madrid3.jpg"),
};
